name: Hydromaze-Admin

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:80"
 # read from environment
    # or use env_file: .env