name: CD

on:
    push:
        branches: master
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: deployment
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
            
            - name: Login to DOcker
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKET_PAT }}
              
            - name: Build and push Docker images
              uses: docker/build-push-action@v4
              with:
                    context: . 
                    push: true
                    tags: shannonjohn/hydromaze-admin-frontend:latest

            - name: Build and push Docker images
              uses: docker/build-push-action@v4
              with:
                    context: ./server 
                    push: true
                    tags: shannonjohn/hydromaze-admin-backend:latest
            
           
            - name: Copy Docker Compose file to server
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ec2-user
                  key: ${{ secrets.SSH_KEY }}
                  source: "docker/docker-compose.yml"
                  target: "~/"

            - name: Deploy to server
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ec2-user
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                    docker-compose -f ~/docker-compose.yml pull
                    docker-compose -f ~/docker-compose.yml up -d --remove-orphans