name: CD

on:
    push:
        branches: master
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: deployment
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
            
            - name: Login to DOcker
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKET_PAT }}
              
            - name: Build and push Docker images
              uses: docker/build-push-action@v4
              with:
                    context: . 
                    push: true
                    tags: shannonjohn/hydromaze-admin-frontend:latest

            - name: Build and push Docker images
              uses: docker/build-push-action@v4
              with:
                    context: ./server 
                    push: true
                    tags: shannonjohn/hydromaze-admin-backend:latest
